apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iss-api
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - iss-api.example.com
      secretName: iss-api-tls
  rules:
    - host: iss-api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: iss-api
                port:
                  number: 8000
