apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iss-anomaly-system

labels:
  - pairs:
      app.kubernetes.io/name: iss-anomaly-detection
      app.kubernetes.io/part-of: iss-anomaly-platform

resources:
  - ingress.yaml
