apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../all
  - ../edge

patches:
  - target:
      kind: ConfigMap
      name: iss-anomaly-config
    patch: |-
      - op: replace
        path: /data/APP_BASE_URL
        value: https://iss-api.moritzknodler.com
      - op: replace
        path: /data/CORS_ALLOW_ORIGINS
        value: https://iss-anomaly-detection.moritzknodler.com
  - target:
      kind: Ingress
      name: iss-api
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: iss-api.moritzknodler.com
      - op: replace
        path: /spec/rules/0/host
        value: iss-api.moritzknodler.com
      - op: replace
        path: /spec/tls/0/secretName
        value: iss-api-moritzknodler-com-tls
